//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportDesigner.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("server=103.97.125.254;user id=mrendzpc_mrend;database=mrendzpc_CoffeeManagement;p" +
            "assword=Hien1712")]
        public string mrendzpc_CoffeeManagement {
            get {
                return ((string)(this["mrendzpc_CoffeeManagement"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("server=103.97.125.254;user id=mrendzpc_llhh;password=Longhuynh;database=mrendzpc_" +
            "CoffeeManagement")]
        public string mrendzpc_CoffeeManagementConnectionString {
            get {
                return ((string)(this["mrendzpc_CoffeeManagementConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("server=103.97.125.254;user id=mrendzpc_llhh;database=mrendzpc_CoffeeManagement;pa" +
            "ssword=Longhuynh;persistsecurityinfo=True")]
        public string mrendzpc_CoffeeManagementConnectionString1 {
            get {
                return ((string)(this["mrendzpc_CoffeeManagementConnectionString1"]));
            }
        }
    }
}
